package com.example.economix_android.Model.presupuestos;

import android.os.Bundle;import android.view.*;import android.widget.*;
import androidx.annotation.*;import androidx.fragment.app.Fragment;import androidx.navigation.*;import androidx.recyclerview.widget.LinearLayoutManager;
import com.example.economix_android.R;import com.example.economix_android.auth.SessionManager;import com.example.economix_android.databinding.FragmentPresupuestosBinding;import com.example.economix_android.network.dto.PresupuestoDto;import com.example.economix_android.network.repository.PresupuestoRepository;import com.example.economix_android.util.ProfileImageUtils;import com.example.economix_android.util.UsuarioAnimationNavigator;import com.google.android.material.dialog.MaterialAlertDialogBuilder;
import java.math.BigDecimal;import java.time.LocalDate;import java.util.*;import retrofit2.*;

public class PresupuestosFragment extends Fragment {
private FragmentPresupuestosBinding binding; private final PresupuestoRepository repository=new PresupuestoRepository(); private final Map<Integer,String> chipCategoryMap=new HashMap<>(); private PresupuestoAdapter adapter; private PresupuestoDto presupuestoSeleccionado;
private final String[] meses={"Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto","Septiembre","Octubre","Noviembre","Diciembre"};
@Nullable @Override public View onCreateView(@NonNull LayoutInflater i,@Nullable ViewGroup c,@Nullable Bundle b){binding=FragmentPresupuestosBinding.inflate(i,c,false);return binding.getRoot();}
@Override public void onViewCreated(@NonNull View v,@Nullable Bundle b){super.onViewCreated(v,b);initChipCategoryMap();setupMonthYearDropdowns();setupQuickAmountButtons();setupRecycler();ProfileImageUtils.applyProfileImage(requireContext(),binding.btnPerfilPres);binding.btnPerfilPres.setOnClickListener(x-> UsuarioAnimationNavigator.playAndNavigate(x,R.id.usuario,R.raw.usuario,6500f,8000f));binding.btnAyudaPres.setOnClickListener(x->mostrarAyuda());binding.btnGuardarPres.setOnClickListener(x->guardarPresupuesto());binding.btnEliminarPres.setOnClickListener(x->eliminarPresupuestoSeleccionado());binding.btnLimpiarPres.setOnClickListener(x->limpiarCampos());View.OnClickListener nav=l->{int id=l.getId();if(id==R.id.navGastos)navigateSafely(l,R.id.navigation_gastos);else if(id==R.id.navIngresos)navigateSafely(l,R.id.navigation_ingresos);else if(id==R.id.navAhorro)navigateSafely(l,R.id.navigation_ahorro);else if(id==R.id.navGraficas)navigateSafely(l,R.id.navigation_graficas);else if(id==R.id.navMenuMini)navigateSafely(l,R.id.menu);};binding.navGastos.setOnClickListener(nav);binding.navIngresos.setOnClickListener(nav);binding.navAhorro.setOnClickListener(nav);binding.navGraficas.setOnClickListener(nav);binding.navMenuMini.setOnClickListener(nav);LocalDate n=LocalDate.now();binding.etMesPres.setText(String.valueOf(n.getMonthValue()));binding.etAnioPres.setText(String.valueOf(n.getYear()));cargarPresupuestosPeriodoActual();}
private void initChipCategoryMap(){chipCategoryMap.put(R.id.chipPresAlimentacion,getString(R.string.cat_alimentacion));chipCategoryMap.put(R.id.chipPresTransporte,getString(R.string.cat_transporte));chipCategoryMap.put(R.id.chipPresEntretenimiento,getString(R.string.cat_entretenimiento));chipCategoryMap.put(R.id.chipPresSalud,getString(R.string.cat_salud));chipCategoryMap.put(R.id.chipPresEducacion,getString(R.string.cat_educacion));chipCategoryMap.put(R.id.chipPresServicios,getString(R.string.cat_servicios));chipCategoryMap.put(R.id.chipPresHogar,getString(R.string.cat_hogar));chipCategoryMap.put(R.id.chipPresOtro,getString(R.string.cat_otro));}
private void setupMonthYearDropdowns(){binding.etMesPres.setOnFocusChangeListener((v,h)->{if(!h)cargarPresupuestosPeriodoActual();});binding.etAnioPres.setOnFocusChangeListener((v,h)->{if(!h)cargarPresupuestosPeriodoActual();});}
private void setupQuickAmountButtons(){binding.btnMonto500.setOnClickListener(v->binding.etMontoMaxPres.setText("500"));binding.btnMonto1000.setOnClickListener(v->binding.etMontoMaxPres.setText("1000"));binding.btnMonto2500.setOnClickListener(v->binding.etMontoMaxPres.setText("2500"));binding.btnMonto5000.setOnClickListener(v->binding.etMontoMaxPres.setText("5000"));}
private void setupRecycler(){adapter=new PresupuestoAdapter(this::cargarPresupuestoEnFormulario);binding.rvPresupuestos.setLayoutManager(new LinearLayoutManager(requireContext()));binding.rvPresupuestos.setAdapter(adapter);}
private void cargarPresupuestosPeriodoActual(){Integer u=SessionManager.getUserId(requireContext());Integer m=getMesSeleccionado();Integer a=getAnioSeleccionado();if(u==null||m==null||a==null){return;} repository.obtenerPresupuestosPorPeriodo(u,m,a,new Callback<List<PresupuestoDto>>(){public void onResponse(Call<List<PresupuestoDto>> c,Response<List<PresupuestoDto>> r){List<PresupuestoDto> body=r.body()==null?Collections.emptyList():r.body();adapter.submitList(body);binding.tvPresupuestosVacio.setVisibility(body.isEmpty()?View.VISIBLE:View.GONE);binding.rvPresupuestos.setVisibility(body.isEmpty()?View.GONE:View.VISIBLE);}public void onFailure(Call<List<PresupuestoDto>> c,Throwable t){Toast.makeText(requireContext(),R.string.mensaje_error_servidor,Toast.LENGTH_SHORT).show();}});} private void cargarPresupuestos(){cargarPresupuestosPeriodoActual();}
private String getSelectedCategory(){int id=binding.chipGroupCategoriaPres.getCheckedChipId();return id==-1?null:chipCategoryMap.get(id);} private Integer getMesSeleccionado(){try{int m=Integer.parseInt(binding.etMesPres.getText().toString().trim());return (m>=1&&m<=12)?m:null;}catch(Exception e){return null;}} private Integer getAnioSeleccionado(){try{int a=Integer.parseInt(binding.etAnioPres.getText().toString().trim());return a>0?a:null;}catch(Exception e){return null;}}
private void guardarPresupuesto(){Integer idUsuario=SessionManager.getUserId(requireContext());if(idUsuario==null){Toast.makeText(requireContext(),R.string.error_usuario_no_autenticado,Toast.LENGTH_SHORT).show();return;}String categoria=getSelectedCategory();String montoTxt=binding.etMontoMaxPres.getText()!=null?binding.etMontoMaxPres.getText().toString().trim():"";Integer mes=getMesSeleccionado();Integer anio=getAnioSeleccionado();if(categoria==null||montoTxt.isEmpty()||mes==null||anio==null){Toast.makeText(requireContext(),R.string.error_campos_presupuesto,Toast.LENGTH_SHORT).show();return;}BigDecimal monto;try{monto=new BigDecimal(montoTxt);}catch(Exception e){Toast.makeText(requireContext(),R.string.error_monto_presupuesto,Toast.LENGTH_SHORT).show();return;}if(monto.compareTo(BigDecimal.ZERO)<=0){Toast.makeText(requireContext(),R.string.error_monto_presupuesto,Toast.LENGTH_SHORT).show();return;}PresupuestoDto dto=PresupuestoDto.builder().idUsuario(idUsuario).categoria(categoria).montoMaximo(monto).mes(mes).anio(anio).build();Callback<PresupuestoDto> cb=new Callback<PresupuestoDto>(){public void onResponse(Call<PresupuestoDto> c,Response<PresupuestoDto> r){if(r.isSuccessful()){Toast.makeText(requireContext(),presupuestoSeleccionado==null?R.string.mensaje_presupuesto_guardado:R.string.mensaje_presupuesto_actualizado,Toast.LENGTH_SHORT).show();limpiarCampos();cargarPresupuestosPeriodoActual();}else if(r.code()==409){Toast.makeText(requireContext(),R.string.error_presupuesto_duplicado,Toast.LENGTH_SHORT).show();}else if(r.code()==400){Toast.makeText(requireContext(),R.string.error_campos_presupuesto,Toast.LENGTH_SHORT).show();}else if(r.code()==404){Toast.makeText(requireContext(),"No se encontró el presupuesto.",Toast.LENGTH_SHORT).show();}else{Toast.makeText(requireContext(),R.string.mensaje_error_operacion,Toast.LENGTH_SHORT).show();}}public void onFailure(Call<PresupuestoDto> c,Throwable t){Toast.makeText(requireContext(),R.string.mensaje_error_servidor,Toast.LENGTH_SHORT).show();}}; if(presupuestoSeleccionado==null)repository.guardarPresupuesto(dto,cb); else repository.actualizarPresupuesto(presupuestoSeleccionado.getIdPresupuesto(),dto,cb);} private void editarPresupuestoSeleccionado(){guardarPresupuesto();}
private void eliminarPresupuestoSeleccionado(){if(presupuestoSeleccionado==null||presupuestoSeleccionado.getIdPresupuesto()==null){Toast.makeText(requireContext(),"Selecciona un presupuesto para eliminar.",Toast.LENGTH_SHORT).show();return;} repository.eliminarPresupuesto(presupuestoSeleccionado.getIdPresupuesto(),new Callback<Void>(){public void onResponse(Call<Void> c,Response<Void> r){if(r.isSuccessful()){Toast.makeText(requireContext(),R.string.mensaje_presupuesto_eliminado,Toast.LENGTH_SHORT).show();limpiarCampos();cargarPresupuestosPeriodoActual();}else Toast.makeText(requireContext(),R.string.mensaje_error_operacion,Toast.LENGTH_SHORT).show();}public void onFailure(Call<Void> c,Throwable t){Toast.makeText(requireContext(),R.string.mensaje_error_servidor,Toast.LENGTH_SHORT).show();}});} private void limpiarCampos(){binding.chipGroupCategoriaPres.clearCheck();binding.etMontoMaxPres.setText("");LocalDate n=LocalDate.now();binding.etMesPres.setText(String.valueOf(n.getMonthValue()));binding.etAnioPres.setText(String.valueOf(n.getYear()));presupuestoSeleccionado=null;binding.btnGuardarPres.setText(R.string.label_guardar);binding.btnEliminarPres.setEnabled(false);} private void cargarPresupuestoEnFormulario(PresupuestoDto p){presupuestoSeleccionado=p;for(Map.Entry<Integer,String>e:chipCategoryMap.entrySet()) if(Objects.equals(e.getValue(),p.getCategoria())){binding.chipGroupCategoriaPres.check(e.getKey());break;} binding.etMontoMaxPres.setText(p.getMontoMaximo()!=null?p.getMontoMaximo().toPlainString():"");binding.etMesPres.setText(String.valueOf(p.getMes()));binding.etAnioPres.setText(String.valueOf(p.getAnio()));binding.btnGuardarPres.setText(R.string.label_actualizar);binding.btnEliminarPres.setEnabled(true);} private void mostrarAyuda(){new MaterialAlertDialogBuilder(requireContext()).setTitle(R.string.titulo_ayuda_presupuestos).setMessage(R.string.mensaje_ayuda_presupuestos).setPositiveButton(android.R.string.ok,null).show();}
private void navigateSafely(View view,int destinationId){NavController n=Navigation.findNavController(view);NavDestination c=n.getCurrentDestination();if(c==null||c.getId()!=destinationId)n.navigate(destinationId);} @Override public void onDestroyView(){super.onDestroyView();binding=null;}
}
