package com.example.economix_android.Model.presupuestos;

import android.view.*;import android.widget.*;
import androidx.annotation.NonNull;import androidx.core.content.ContextCompat;import androidx.recyclerview.widget.RecyclerView;
import com.example.economix_android.R;import com.example.economix_android.network.dto.PresupuestoDto;
import java.math.BigDecimal;import java.text.NumberFormat;import java.util.*;
public class PresupuestoAdapter extends RecyclerView.Adapter<PresupuestoAdapter.PresupuestoViewHolder>{
public interface OnPresupuestoClickListener{void onPresupuestoClick(PresupuestoDto presupuesto);} private final List<PresupuestoDto>data=new ArrayList<>(); private final OnPresupuestoClickListener listener; private final NumberFormat currency=NumberFormat.getCurrencyInstance(new Locale("es","MX"));
public PresupuestoAdapter(OnPresupuestoClickListener listener){this.listener=listener;} public void submitList(List<PresupuestoDto>n){data.clear();if(n!=null)data.addAll(n);notifyDataSetChanged();}
@NonNull @Override public PresupuestoViewHolder onCreateViewHolder(@NonNull ViewGroup p,int v){return new PresupuestoViewHolder(LayoutInflater.from(p.getContext()).inflate(R.layout.item_presupuesto,p,false));}
@Override public void onBindViewHolder(@NonNull PresupuestoViewHolder h,int i){PresupuestoDto d=data.get(i);h.tvCategoria.setText(d.getCategoria());h.tvPeriodo.setText((d.getMes()!=null?d.getMes():0)+"/"+(d.getAnio()!=null?d.getAnio():0));h.tvMax.setText(h.itemView.getContext().getString(R.string.label_monto_maximo_presupuesto,fmt(d.getMontoMaximo())));h.tvGastado.setText(h.itemView.getContext().getString(R.string.label_monto_gastado_presupuesto,fmt(d.getMontoGastado())));h.tvRestante.setText(h.itemView.getContext().getString(R.string.label_monto_restante_presupuesto,fmt(d.getMontoRestante())));int pct=d.getPorcentajeUso()==null?0:d.getPorcentajeUso().intValue();pct=Math.max(0,Math.min(100,pct));h.tvPct.setText(h.itemView.getContext().getString(R.string.label_porcentaje_presupuesto,pct));h.progress.setProgress(pct);String estado=d.getEstado()==null?"NORMAL":d.getEstado();h.tvEstado.setText(h.itemView.getContext().getString(R.string.label_estado_presupuesto,estado));int color=R.color.tealAccent;if("EXCEDIDO".equalsIgnoreCase(estado))color=R.color.module_gastos;else if("ADVERTENCIA".equalsIgnoreCase(estado))color=R.color.goldAccent;h.tvEstado.setTextColor(ContextCompat.getColor(h.itemView.getContext(),color));h.itemView.setOnClickListener(v->listener.onPresupuestoClick(d));}
private String fmt(BigDecimal v){return currency.format(v==null?BigDecimal.ZERO:v);} @Override public int getItemCount(){return data.size();}
static class PresupuestoViewHolder extends RecyclerView.ViewHolder{TextView tvCategoria,tvPeriodo,tvMax,tvGastado,tvRestante,tvPct,tvEstado;ProgressBar progress;PresupuestoViewHolder(@NonNull View i){super(i);tvCategoria=i.findViewById(R.id.tvCategoriaPresupuesto);tvPeriodo=i.findViewById(R.id.tvPeriodoPresupuesto);tvMax=i.findViewById(R.id.tvMontoMaximoPresupuesto);tvGastado=i.findViewById(R.id.tvMontoGastadoPresupuesto);tvRestante=i.findViewById(R.id.tvMontoRestantePresupuesto);tvPct=i.findViewById(R.id.tvPorcentajePresupuesto);tvEstado=i.findViewById(R.id.tvEstadoPresupuesto);progress=i.findViewById(R.id.progressPresupuesto);}}
}
